version: '3.8'

services:
  langchain-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: langchain_api_container
    ports:
      - "8000:8000"  # api_server.py的端口
      - "8001:8001"  # api_rag_knowledge.py的端口
      - "8002:8002"  # api_feishu_knowledge.py的端口
    environment:
      - PYTHONUNBUFFERED=1
      - API_SERVER_PORT=${API_SERVER_PORT}
      - RAG_API_PORT=${RAG_API_PORT}
      - FEISHU_API_PORT=${FEISHU_API_PORT}
    volumes:
      - ..:/app  # 挂载项目目录，便于开发时实时更新代码
    networks:
      - langchain-network
    restart: unless-stopped

networks:
  langchain-network:
    driver: bridge